import { useEffect, useRef, useState } from 'react'
import { X, Loader2, CheckCircle2, XCircle, Clock, Smartphone } from 'lucide-react'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'
import { formatKsh } from '@/lib/format'
import { initiateSTKPush, getMpesaStatus } from '@/api/mpesa'