import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import api from '@/api/client'
import CloseMetersForm from '@/features/shifts/CloseMetersForm'
import { formatDateTime, formatKsh } from '@/lib/format'
import Badge from '@/components/ui/Badge'
