import { useEffect, useState } from 'react'
import TankList from '@/features/tanks/TankList'
import DipReadingForm from '@/features/tanks/DipReadingForm'
import DeliveryForm from '@/features/tanks/DeliveryForm'
import { listTanks } from '@/api/tanks'
import Button from '@/components/ui/Button'
import { X } from 'lucide-react'
