import { useState } from 'react'
import { Loader2 } from 'lucide-react'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'
import { createUser } from '@/api/users'
import { ROLE } from '@/lib/roles'